
## This file contains the default values for configuration's variables.

# BINDIR    := /usr/local/bin

# OCAMLDUCE := NO

# PROJECTS := tutorial eliom js_of_ocaml tyxml lwt macaque oclosure server

# SRCROOT         := ../src
# LWT_DIR         := ${SRCROOT}/lwt
# JS_OF_OCAML_DIR := ${SRCROOT}/js_of_ocaml
# SERVER_DIR      := ${SRCROOT}/ocsigenserver
# ELIOM_DIR       := ${SRCROOT}/eliom
# OCLOSURE_DIR    := ${SRCROOT}/oclosure
# MACAQUE_DIR     := ${SRCROOT}/macaque
# TUTORIAL_DIR    := ${SRCROOT}/tutorial

# OCAMLFIND     := ocamlfind
# OCAMLDUCEFIND := ocamlducefind

# OCAMLDOC     := ${OCAMLFIND} ocamldoc
# OCAMLDUCEDOC := ${OCAMLDUCEFIND} ocamldoc

# OCAMLC       := ${OCAMLFIND} ocamlc
# OCAMLDUCEC   := ${OCAMLDUCEFIND} ocamlc
# OCAMLOPT     := ${OCAMLFIND} ocamlopt
# OCAMLDUCEOPT := ${OCAMLDUCEFIND} ocamlopt
# OCAMLDEP     := ${OCAMLFIND} ocamldep
# OCAMLDUCEDEP := ${OCAMLDUCEFIND} ocamldep
# OCAMLLEX     := ocamllex

# OCAMLDOCPATH := $(shell ${OCAMLFIND} printconf stdlib)/ocamldoc
# COMPILERLIBSPARSING := \
	# -I $(shell ${OCAMLFIND} printconf stdlib)/compiler-libs/parsing \
	# -I $(shell ${OCAMLFIND} printconf stdlib)/compiler-libs/typing

# OCAMLDUCEDOCPATH := $(shell ${OCAMLDUCEFIND} printconf stdlib)/ocamlduce/ocamldoc
# COMPILERDUCELIBSPARSING := \
	# -I $(shell ${OCAMLFIND} printconf stdlib)/ocamlduce/compiler-libs/parsing \
	# -I $(shell ${OCAMLFIND} printconf stdlib)/ocamlduce/compiler-libs/typing

# INSTALL := INSTALL